// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// waylearn:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfbAAE61WGyMb6t4seStoNM5mwonSdOA8',
    appId: '1:32146242382:web:31cc4f71a4043c9b9efc1f',
    messagingSenderId: '32146242382',
    projectId: 'waytolearn-3ebca',
    authDomain: 'waytolearn-3ebca.firebaseapp.com',
    databaseURL: 'https://waytolearn-3ebca-default-rtdb.firebaseio.com',
    storageBucket: 'waytolearn-3ebca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiCL99Yih3xeCDRkIhICLs4RbixP8AmQ4',
    appId: '1:32146242382:android:4d8bca0d9797f1269efc1f',
    messagingSenderId: '32146242382',
    projectId: 'waytolearn-3ebca',
    databaseURL: 'https://waytolearn-3ebca-default-rtdb.firebaseio.com',
    storageBucket: 'waytolearn-3ebca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpw7US9n0k82VXDAftexJcNMPQ1Zafesc',
    appId: '1:32146242382:ios:6733b228befa0ef89efc1f',
    messagingSenderId: '32146242382',
    projectId: 'waytolearn-3ebca',
    databaseURL: 'https://waytolearn-3ebca-default-rtdb.firebaseio.com',
    storageBucket: 'waytolearn-3ebca.appspot.com',
    iosBundleId: 'com.waylearn.waytolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpw7US9n0k82VXDAftexJcNMPQ1Zafesc',
    appId: '1:32146242382:ios:6733b228befa0ef89efc1f',
    messagingSenderId: '32146242382',
    projectId: 'waytolearn-3ebca',
    databaseURL: 'https://waytolearn-3ebca-default-rtdb.firebaseio.com',
    storageBucket: 'waytolearn-3ebca.appspot.com',
    iosBundleId: 'com.waylearn.waytolearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfbAAE61WGyMb6t4seStoNM5mwonSdOA8',
    appId: '1:32146242382:web:9dda596d1f07642f9efc1f',
    messagingSenderId: '32146242382',
    projectId: 'waytolearn-3ebca',
    authDomain: 'waytolearn-3ebca.firebaseapp.com',
    databaseURL: 'https://waytolearn-3ebca-default-rtdb.firebaseio.com',
    storageBucket: 'waytolearn-3ebca.appspot.com',
  );
}
